name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 2.1.0
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: ">=2.6.0 <3.3.7"

dependencies:
 typed_data: '^1.3.1'
 event_bus: '^2.0.0'
 path: '^1.8.2'
 crypto: '^3.0.2'
 meta: '^1.8.0'
 observable: '^0.24.0'

dev_dependencies:
 test: '^1.22.0'
 mockito: '^5.3.2'
 pedantic: '^1.11.1'
 pana: '^0.21.21'
 build_runner: '^2.3.2'
 build_test: '^2.1.5'
 build_web_compilers: '^3.2.7'





